server:
  servlet:
    context-path: /
  port: 9090
  compression:
    enable: true
    mime-types:
      - application/json
      - text/html
      - text/xml
spring:
  application:
    name: demo-test
  output:
    ansi:
      enabled: DETECT
  http:
    encoding:
      charset: UTF-8
  datasource:
    url: jdbc:postgresql://localhost:5432/people_service
    username: people_service
    password: people_service
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        generate_statistics: false
